Feature/implement flashcard functionallity #48
coders-factory-com/cf-backend pull request #49
Opened 2023-07-14 13:22 UTC by paweu9000

2023-07-14 15:34 UTC, dawciobiel commented on src/main/java/com/codersfactory/flashcards/FlashcardCollectionsService.java
> +    FlashcardCollection mapDto(CreateFlashcardCollectionDto dto) {
This method should be named as `mapDTO`. Because DTO is _Data Transfer Object_. Mean three words. Every first letter typed by capital letter.
Another example of naming convention is:
`findById` - is correct. Why? Because `Id` is _Identifier_. Mean one word.

2023-07-14 15:34 UTC, dawciobiel commented on src/main/java/com/codersfactory/flashcards/FlashcardCollectionsService.java
> +    FlashcardCollectionDto toDto(FlashcardCollection collection) {
Same here with `toDto` -> `toDTO`

2023-07-14 15:35 UTC, dawciobiel commented on src/main/java/com/codersfactory/flashcards/FlashcardCollectionsService.java
> +    public FlashcardCollection saveByDto(CreateFlashcardCollectionDto dto) {
save here with `saveByDto` -> `saveByDTO`

2023-07-14 15:54 UTC, dawciobiel reviewed
Request changes

2023-07-14 15:54 UTC, dawciobiel commented on src/main/java/com/codersfactory/flashcards/FlashcardController.java
> +        return new ResponseEntity<>(collectionsService.findById(id), HttpStatusCode.valueOf(200));
```suggestion
        return new ResponseEntity<>(collectionsService.findById(id), HttpStatus.OK);
```
or

```java
ResponseEntity<FlashcardCollection> flashCollections = collectionsService.findById(id);
HttpsStatus httpStatus = HttpStatus.OK;
ResponseEntity response = new ResponseEntity<>(flashCollections,  httpStatus);

return  response;
```

2023-07-14 15:54 UTC, dawciobiel commented on src/main/java/com/codersfactory/flashcards/FlashcardController.java
> +    ResponseEntity<FlashcardCollection> createCollection(@RequestBody CreateFlashcardCollectionDto dto) {
What kind of collection creates this method?
```java
List<SomeKindOfFunnyThing> EmptyList = Collections.<SomeKindOfFunnyThing>emptyList(); // by Guava by Google
```
:)

maybe `createFlashcardCollection` ?

2023-07-14 15:54 UTC, dawciobiel commented on src/main/java/com/codersfactory/flashcards/FlashcardsService.java
> +    final FlashcardsMapper mapper = FlashcardsMapper.INSTANCE;
Please add an empty line between every class field. 
And an empty line between fields and the constructor.
And an empty line between every method.

2023-07-14 16:02 UTC, dawciobiel commented on src/test/java/com/codersfactory/flashcards/FlashcardsServiceTest.java
> +        service.saveEntity(flashcard);
This method is not implemented in `FlashcardsService` service.

2023-07-14 16:02 UTC, dawciobiel commented on src/test/java/com/codersfactory/flashcards/FlashcardsServiceTest.java
> +        service.deleteById(1L);
This method is not implemented in `FlashcardsService` service.

2023-07-14 16:06 UTC, dawciobiel requested changes
changes required

2023-07-14 16:06 UTC, dawciobiel commented on src/main/java/com/codersfactory/flashcards/Flashcard.java
> +import lombok.*;
Please do not use an asterisk for importing packages.
https://doc.nuxeo.com/corg/intellij-idea-setup/

2023-07-16 00:33 UTC, sylvvester requested changes
Request changes: Please consider refactoring the remaining tests to follow the same convention used in the provided example.

2023-07-16 00:33 UTC, sylvvester commented on src/test/java/com/codersfactory/flashcards/FlashcardsServiceTest.java
> +    @Test
In our tests, we adhere to the Behavior-Driven Development (BDD) convention. BDD focuses on describing the behavior of the system through clear and descriptive test names. The given-when-then structure is followed in test methods to provide better readability and understanding of test scenarios.

We utilize BDDMockito's stubbing methods to mock the repository's behavior effectively. The `given()` method from BDDMockito is used for stubbing the `findById()` method to return an optional containing a pre-defined Flashcard entity.

Additionally, in multiple tests, if certain constant values are used repeatedly, we create private static fields to store these values. This approach improves code maintenance and readability for example: 

```java
private static long ID_1L = 1L;
private static String BACK = "back"; // or FLASHCARD_BACK
```

Here's an example test method, adhering to the BDD convention:
    
```java
    @DisplayName("Should return flashcard with given id")
    @Test
    public void whenFindFlashcardById_ThenCorrectFlashcardShouldBeReturned() {
        //given
        FlashcardCollection flashcardCollection = new FlashcardCollection();
        flashcardCollection.setId(ID_1L);

        Flashcard flashcard = new Flashcard(ID_1L, FRONT, BACK, flashcardCollection);
        given(repository.findById(ID_1L).willReturn(Optional.of(flashcard));

        //when
        Flashcard result = service.findById(ID_1L);

        //then
        assertThat(result, is(equalTo(flashcard)));
    }
```
Additionally, consider creating a helper method to facilitate the creation of a Flashcard entity with predefined values for testing purposes. This helper method can be used to avoid redundancy in test code and enhance test readability by providing a standardized way to generate Flashcard objects with specific properties. However, by introducing a helper method like this, any changes or updates to the fields of the Flashcard entity can be easily managed in a single location. 

```java
private Flashcard createFlashcardEntity() {
        FlashcardCollection flashcardCollection = new FlashcardCollection();
        flashcardCollection.setId(ID_1L);
        
        return new Flashcard(ID_1L, FRONT, BACK, flashcardCollection);
    }
```
Feel free to explore the test suite in this repository: [link](https://github.com/Simple-as-Coding/tutoring-platform/blob/develop/src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java). The tests in this repository are well-implemented and adhere to the Behavior-Driven Development (BDD) convention, serving as valuable examples to understand how to write effective and well-structured tests.

2023-07-16 00:37 UTC, sylvvester commented on src/test/java/com/codersfactory/flashcards/FlashcardsServiceTest.java
> +    }
In our tests, we adhere to the Behavior-Driven Development (BDD) convention. BDD focuses on describing the behavior of the system through clear and descriptive test names. The given-when-then structure is followed in test methods to provide better readability and understanding of test scenarios.

We utilize BDDMockito's stubbing methods to mock the repository's behavior effectively. The `given()` method from BDDMockito is used for stubbing the `findById()` method to return an optional containing a pre-defined Flashcard entity.

Additionally, in multiple tests, if certain constant values are used repeatedly, we create private static fields to store these values. This approach improves code maintenance and readability for example: 

```java
private static long ID_1L = 1L;
private static String BACK = "back"; // or FLASHCARD_BACK
```

Here's an example test method, adhering to the BDD convention:
    
```java
    @DisplayName("Should return flashcard with given id")
    @Test
    public void whenFindFlashcardById_ThenCorrectFlashcardShouldBeReturned() {
        //given
        FlashcardCollection flashcardCollection = new FlashcardCollection();
        flashcardCollection.setId(ID_1L);

        Flashcard flashcard = new Flashcard(ID_1L, FRONT, BACK, flashcardCollection);
        given(repository.findById(ID_1L).willReturn(Optional.of(flashcard));

        //when
        Flashcard result = service.findById(ID_1L);

        //then
        assertThat(result, is(equalTo(flashcard)));
    }
```
Additionally, consider creating a helper method to facilitate the creation of a Flashcard entity with predefined values for testing purposes. This helper method can be used to avoid redundancy in test code and enhance test readability by providing a standardized way to generate Flashcard objects with specific properties. However, by introducing a helper method like this, any changes or updates to the fields of the Flashcard entity can be easily managed in a single location. 

```java
private Flashcard createFlashcardEntity() {
        FlashcardCollection flashcardCollection = new FlashcardCollection();
        flashcardCollection.setId(ID_1L);
        
        return new Flashcard(ID_1L, FRONT, BACK, flashcardCollection);
    }
```
Feel free to explore the test suite in this repository: [link](https://github.com/Simple-as-Coding/tutoring-platform/blob/develop/src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java). The tests in this repository are well-implemented and adhere to the Behavior-Driven Development (BDD) convention, serving as valuable examples to understand how to write effective and well-structured tests.

2023-07-24 15:37 UTC, sylvvester approved these changes

2023-07-24 15:37 UTC, merged